import React, { useState, useEffect } from "react";
import Word from "./Word";
import Letters from "./Letters";
import Categories from "./Categories";



const Hangman = () => {

    const wordIsGuessed = () => {
        return selectedWord.split("").every(letter => guessedLetters.includes(letter));
      };
  
    const randomWordFromCategory = (category) => {
        const randomIndex = Math.floor(Math.random() * category.words.length);
        return category.words[randomIndex];
    };

  
    const categories = [
        { name: "Animals", words: ["DOG", "CAT", "ELEPHANT"] },
        { name: "Cities", words: ["PARIS", "LONDON", "TOKYO"] },
        { name: "Colors", words: [
             "TATTLETALE GREY", "YELLOW GREEN", "PURPLISH BLUE", "PEACH", "EMERALD", "SOOT BLACK", "BLUE", "GREEN","UNDERTONE", 
             "SEPIA", "IVORY", "JADE GREEN", "PALENESS", "WANNESS", "BLUISH GREEN", "BLEACH", "PURPLISH-RED", "DRAB", "SILVER GREY", 
             "DAVY'S GRAY", "PALLIDNESS", "DARKNESS", "GRAY", "NAVY BLUE", "BLUENESS", "BURGUNDY", "DARK BLUE", "INDIGO", "PURPLISH PINK", 
             "BOTTLE GREEN", "PALE YELLOW", "DITHERED COLOR", "INKINESS", "POWDER BLUE", "REDDISH BROWN", "PUCE", "PRIMARY COLOR", "ORANGE RED", 
             "BLONDE", "AZURE", "AMBER", "LIGHT BROWN", "WINE-COLORED", "TURQUOISE", "TINCTURE", "VERMILION", "ROSINESS", "OLIVE BROWN", 
             "CHARCOAL GRAY", "SCARLET", "TONE", "BUFF", "WINE-COLOURED", "VIOLET", "MAGENTA", "YELLOWISH BROWN", "MAHOGANY", "ALIZARINE RED", 
             "WHITENESS", "JET BLACK", "CHALK", "CHROME GREEN", "PITCH BLACK", "BURNT UMBER", "LAVENDER", "PRIMARY COLOR FOR LIGHT", "FAWN", "PIGMENTATION", 
             "COPPER COLOR", "WINE", "IRON-GRAY", "ORANGE", "SILVER GRAY", "HEATHER", "RED", "TANGERINE", "HOARINESS", "REDNESS", "ECRU", "CERULEAN", 
             "WARNING COLORATION", "GREENISHNESS", "PARIS GREEN", "CHROMATIC COLOR", "REDDISH BLUE", "BONE", "TYRIAN PURPLE", "DAVY'S GREY", "INDIAN RED", 
             "PRUSSIAN BLUE", "TAUPE", "OLD ROSE", "PROTECTIVE COLORATION", "SAFFRON", "PRIMARY COLOR FOR PIGMENTS", "UMBER", "ORANGENESS", "TINT", 
             "DAPPLED-GREY", "ROYAL BLUE", "GOLD", "DEEP BROWN", "COPPER", "MAROON", "OCHRE", "CHROMATISM", "HEATHER MIXTURE", "PALLOR", "CARAMEL", "BLOND", 
             "CHARCOAL", "TAN", "DUN", "DAPPLE-GRAY", "GREYISH BROWN", "ROYAL PURPLE", "HAZEL", "OLIVE", "CANARY", "BROWN", "BLUE GREEN", "SHADE", "BRICK RED", 
             "DEPIGMENTATION", "CHROMATIC COLOUR", "PRIMARY SUBTRACTIVE COLOR FOR LIGHT", "CORAL", "TATTLETALE GRAY", "MOTTLE", "TINGE", "ASH GREY", 
             "REDDISH ORANGE", "CYAN", "STEEL GRAY", "PEACOCK BLUE", "CHROME RED", "OCHER", "CLARET", "GRAYNESS", "TOPAZ", "SALMON PINK", "CARDINAL", 
             "CRYPTIC COLORATION", "YELLOWISH GREEN", "SWARTHINESS", "DARK RED", "WHEAT", "YELLOWNESS", "STRAW", "SKIN COLOUR", "YELLOW", "BLONDNESS", 
             "GREENISH YELLOW", "CARAMEL BROWN", "ULTRAMARINE", "NONSOLID COLOR", "SANGUINE", "OFF-WHITE", "AQUAMARINE", "COMPLEMENTARY COLOR", "CARNATION", 
             "LURIDNESS", "PURPLE", "BLACKNESS", "ASH GRAY", "COBALT BLUE", "PINK", "MELLOWNESS", "GREENISH BLUE", "OXFORD GREY", "OLIVE DRAB", "IRON BLUE", 
             "CHARTREUSE", "YELLOWISH PINK", "ROSE", "COFFEE", "TAWNINESS", "REDDISH PURPLE", "GAMBOGE", "GREYNESS", "DEEP RED", "COMPLEXION", "BROWNISH YELLOW", 
             "SILVER", "STEEL GREY", "MAIZE", "DUSKINESS", "SALMON", "CERISE", "DITHERED COLOUR", "ACHROMATIC COLOUR", "PURPLENESS", "PASTEL", "CHERRY", 
             "BURNT SIENNA", "PEA GREEN", "SKIN COLOR", "PURPLISH RED", "LEMON YELLOW", "CHARCOAL GREY", "ALABASTER", "SPECTRAL COLOR", "PEARL", "TURKEY RED", 
             "VANDYKE BROWN", "OLD GOLD", "SALLOWNESS", "SAGE GREEN", "CHOCOLATE", "LEMON", "LIVIDNESS", "NAVY", "APRICOT", "MAUVE", "HAIR COLORING", 
             "DAPPLED-GRAY", "SAPPHIRE", "RAW SIENNA", "STEEL BLUE", "CHERRY RED", "FUSCHIA", "WHITE", "COLORATION", "RICHNESS", "RUBY", "APOSEMATIC COLORATION",
             "BEIGE", "OLIVE-GREEN", "FROSTINESS", "APATETIC COLORATION", "BROWNNESS", "CARMINE", "CRIMSON", "BLACK", "VIRIDITY", "ACHROMATIC COLOR", "LIVIDITY", 
             "AQUA", "TEAL", "OXFORD GRAY", "COLOUR", "SEA GREEN", "FAIRNESS", "GREENNESS", "MOCHA", "CANARY YELLOW", "OXBLOOD RED", "COLORING", "COAL BLACK", 
             "RUDDINESS", "SKY-BLUE", "CHESTNUT", "GRAYISH BROWN", "EBONY", "COMPLEMENTARY", "IRON-GREY", "GREY", "SNUFF-COLOR", "VENETIAN RED", "PRIMARY COLOUR", 
             "PINKNESS", "OLIVE GREEN", "SABLE", "DAPPLE-GREY", "JADE", "SPECTRAL COLOUR", "ORANGE YELLOW", "SOLFERINO" ] },
        { name: "Fruits", words: [
            "BARTLETT PEAR","DAMSON","PERSIMMON", "DRAGON'S EYE", "RAPESEED","FLAXSEED","PRAIRIE GOURD","SOUARI NUT","LEGUME","KITEMBILLA","RIVER PEAR",
            "BRAZIL NUT","SECKEL","CUMIN SEED","BING CHERRY","CRAB APPLE","LOGANBERRY","TONKA BEAN","PULASSAN","GRANADILLA","MANGOSTEEN","RAISIN","BEAN",
            "UGLI FRUIT","JONATHAN","OIL NUT","LITCHI","NETTED MELON","JORDAN ALMOND","WILD CHERRY","MANDARIN","NAVEL ORANGE","ROME BEAUTY","FREESTONE",
            "COX'S ORANGE PIPPIN","MELON BALL","ACORN","HUCKLEBERRY","JACK","CHERIMOYA","JUNIPER BERRY","NICKER SEED","PEAR","BULLOCK'S HEART", "PIP","FIG",
            "LONGANBERRY","CHERRY","GRAPE","LENTIL","POND APPLE","STONE FRUIT","GREENGAGE PLUM","CANISTEL","LOQUAT","EDIBLE NUT","PRICKLY PEAR","MUSCADINE",
            "LANSET","GOLDEN DELICIOUS","BARBADOS CHERRY","BANEBERRY","COCONUT","OILSEED","MARANG","BUFFALO NUT","APPLE","SULTANA","SHADBERRY","WALNUT",
            "MUSKMELON","AKEE","JOB'S TEARS","DESSERT APPLE","LITCHEE","SAPODILLA PLUM","PISTACHIO","PYRENE","STAR FRUIT","COLA NUT","PALM KERNEL","GARAMBULLA",
            "GUANABANA","COFFEE BEAN","LICHEE","RYE","CLEMENTINE","ALGARROBA BEAN","APPLE NUT","NUTLET","ANJOU","FALSE FRUIT","MEXICAN BLACK CHERRY","BLACKHEART"
            ,"APRICOT","POME","DEWBERRY","CITRANGE","CALABASH","YELLOW DELICIOUS","PYXIS","BLACK OLIVE","CRANBERRY","CORTLAND","QUANDONG","ACINUS","GENIP",
            "SYCONIUM","RASPBERRY","GARDEN PEA","CHINESE JUJUBE","BOXBERRY","MEDLAR","MOMBIN","NECTARINE","WEST INDIAN CHERRY","CASTOR BEAN","HOG PLUM",
            "CEDAR NUT","VICTORIA PLUM","STAYMAN","ANANAS","GOOBER PEA","NATAL PLUM","AMARELLE","WATERMELON","YELLOW BERRY","SAFFLOWER SEED","ACHENE",
            "SOYA BEAN","YELLOW MOMBIN","KITAMBILLA","CHINQUAPIN","CUMIN","GREEN OLIVE","LANSA","LOCUST POD","EGGFRUIT","BANANA","MACADAMIA NUT","SOYBEAN",
            "PECAN","ARECA NUT","CARYOPSIS","GRAPEFRUIT","POMEGRANATE","PEARMAIN","LANSEH","HIP","DIKA NUT","SUNFLOWER SEED","COWPEA","GARBANZO",
            "QUANDONG NUT","JAPANESE PLUM","CLINGSTONE","SWEET MELON","LINGONBERRY","SPIKE","CERIMAN","MAST","TANGERINE","SUGAR APPLE","MUSCAT",
            "MARASCA","MEXICAN JUMPING BEAN","HONEYDEW","PINE NUT","SYNCARP","BLUEBERRY","MULBERRY","CORN","SCHIZOCARP","AVOCADO","DRIED FRUIT",
            "RIBIER","JAFFA ORANGE","BLACK-EYED PEA","GENIPAP FRUIT","HAGBERRY","CASHEW","SURINAM CHERRY","CHINCAPIN","MACOUN","COHUNE NUT","ANNON",
            "SEVILLE ORANGE","BARLEYCORN","BRAZIL","FAVA BEAN","BLACKHEART CHERRY","SAPODILLA","MANDARIN ORANGE","KIWI","RIPE OLIVE","MAY APPLE",
            "BLACK CURRANT","MAMEY","THOMPSON SEEDLESS","CRABAPPLE","WATER LEMON","BUTTERNUT","HICKORY NUT","BITTER ORANGE","NUTMEG MELON","KETEMBILLA",
            "QUANDANG","OKRA","CATAWBA","UGLI","BOYSENBERRY","FIELD PEA","BLACK WALNUT","COCOA PLUM","NATIVE PEACH","PUMPKIN SEED","PIGNOLIA","FILBERT",
            "LEECHEE","RAMBOTAN","JUMPING SEED","NORTHERN SPY","KOLA NUT","ELDERBERRY","MORELLO","JUJUBE","MOUNTAIN CRANBERRY","NICKER NUT","GRAIN",
            "EAR","DRUPE","SAPOTA","OLIVE","TEABERRY","BACCA","ALMOND","RAMBUTAN","CHERIMOLLA","CASABA MELON","PEA","BLADE APPLE","SWEET CUP","HAZELNUT",
            "AGUACATE","ACCESSORY FRUIT","SOUR CHERRY","OIL-RICH SEED","TANGELO","AVOCADO PEAR","PULASAN","VEGETABLE IVORY","SIMPLE FRUIT","WHEAT BERRY",
            "SOUR ORANGE","SORB APPLE","SCREW BEAN","COCO PLUM","ORANGE","PRUNE","KEY FRUIT","KUMQUAT","AMARANTH","HACKBERRY","PINEAPPLE GUAVA",
            "ANCHOVY PEAR","BARBADOS GOOSEBERRY","SCUPPERNONG","JAK","PASSION FRUIT","SAPOTE","CHINKAPIN","ROWANBERRY","EDIBLE FRUIT","PLUM","SEEDLESS RAISIN",
            "BARTLETT","SLIPSKIN GRAPE","WINTER MELON","GOURD","ALGAROBILLA","MUSCAT GRAPE","PIPPIN","CURRANT","SOY","LITCHI NUT","KAI APPLE","ICACO",
            "NEEM SEED","WINESAP","LOMENT","BROAD BEAN","FEIJOA","CONKER","JAMAICA APPLE","CITRUS","PAPAYA","YELLOW GRANADILLA","CANTALOUPE","WHORTLEBERRY",
            "BULLACE GRAPE", "LANE'S PRINCE ALBERT","COWBERRY","CHESTNUT","CAPITULUM","MCINTOSH","SOUR GOURD","FOX GRAPE","EUROPEAN BLUEBERRY","BLACKBERRY",
            "BERRY","ROSEHIP","LIME","PAWPAW","ILAMA","BEACH PLUM","CUSTARD APPLE","GREENGAGE","MANGO","JACKFRUIT","COUMARA NUT","LICHI","RED DELICIOUS",
            "ELK NUT","BUCKEYE","BREADFRUIT","TAMARINDO","ALGARROBA","PINON NUT","SWEET ORANGE","PAPAW","HONEYDEW MELON","PERSIAN MELON","SERVICEBERRY",
            "BUNYA BUNYA","WINTERGREEN","ENGLISH WALNUT","SPICEBERRY","CASHEW NUT","AGGREGATE FRUIT","CANTALOUP","COTTONSEED","ORDEAL BEAN","CASABA",
            "TEMPLE ORANGE","BUCKTHORN BERRY","WILD PLUM","COBNUT","GROUNDNUT","MEALIE","KERNEL","WATER CHINQUAPIN","COFFEE","SEED","COB","NEWTOWN WONDER",
            "QUINCE","COFFEE BERRY","SPANISH LIME","COWAGE","GOOSEBERRY","VINIFERA GRAPE","IVORY NUT","POD","HEART CHERRY","JUMPING BEAN","BABASSU NUT",
            "DURIAN","EMPEROR","CHECKERBERRY","SECKEL PEAR","ALGARROBILLA","SWEET CALABASH","HORSEBEAN","CHOKECHERRY","ACEROLA","DRUPELET","MULTIPLE FRUIT",
            "FRUIT","CITRON","PISTACHIO NUT","MONKEY NUT","BILBERRY","LINSEED","PSEUDOCARP","BLACK CHERRY","CITRUS FRUIT","KEY LIME","POMELO","SATSUMA",
            "NET MELON","PYXIDIUM","MUSCATEL","SUGARBERRY","ROSE APPLE","JUNEBERRY","SWEET CHERRY","SAMARA","TOKAY","BOSC","DATE","MAMMEE","SWEETSOP",
            "JABOTICABA","BELL APPLE","MONKEY BREAD","CAPULIN","SHADDOCK","BONDUC NUT","CAROB BEAN","BALDWIN","CAROB","ASH-KEY","DRIED APRICOT","PEANUT",
            "GOOBER","GENIPAP","BETEL NUT","GRUGRU NUT","CLING","PLUMCOT","BLUE FIG","LOWBUSH CRANBERRY","DELICIOUS","STAYMAN WINESAP","ALLIGATOR PEAR",
            "EMPIRE","SEEDPOD","SASKATOON","CALABAR BEAN","CHINESE GOOSEBERRY","CHINESE DATE","CARAMBOLA","PEACH","ACKEE","OXHEART","CUBEB","RED CURRANT",
            "COQUILLA NUT","COCOANUT","DIVI-DIVI","CONCORD GRAPE","KIWI FRUIT","MELON","CITROUS FRUIT","KEY","CHICKPEA","STRAWBERRY","PINEAPPLE","LOCUST BEAN",
            "DAMSON PLUM","GUAVA","PALM NUT", "BRAMLEY'S SEEDLING","EATING APPLE","LANSAT","LYCHEE","WINDFALL","MARMALADE PLUM","FRUITLET","FLAME TOKAY","SORB",
            "ROSE HIP","CEMBRA NUT","TAMARIND","PRIMA","SLOE","MONSTERA","QUANTONG","VALENCIA ORANGE","SEEDED RAISIN","PITAHAYA","EDIBLE SEED","BEECHNUT",
            "OXHEART CHERRY","GRANNY SMITH","NUT","EARTHNUT","LEMON","CANDLENUT","COOKING APPLE","CARISSA PLUM","HORSE CHESTNUT","SOURSOP","MAMMEE APPLE"] },
    ];
  
    const [currentCategory, setCurrentCategory] = useState(categories[0]);
    const [selectedWord, setSelectedWord] = useState(randomWordFromCategory(currentCategory));
    const [guessedLetters, setGuessedLetters] = useState([]);
  
    const [showSuccessMessage, setShowSuccessMessage] = useState(false);
    
    useEffect(() => {
        if (showSuccessMessage) {
        const timer = setTimeout(() => {
            setShowSuccessMessage(false);
        }, 3000);

        return () => clearTimeout(timer);
        }
    }, [showSuccessMessage]);

    const handleLetterClick = (letter) => {
        const newGuessedLetters = [...guessedLetters, letter];
        setGuessedLetters(newGuessedLetters);

        if (selectedWord.split("").every(l => newGuessedLetters.includes(l))) {
        setShowSuccessMessage(true); 
        setSelectedWord(randomWordFromCategory(currentCategory));
        setGuessedLetters([]);
        }
    };

    const handleCategorySelect = (category) => {
        setCurrentCategory(category);
        setSelectedWord(randomWordFromCategory(category));
        setGuessedLetters([]); 
    };



    return (
        <div>
          <Categories categories={categories} onSelect={handleCategorySelect} />
          <h2>Category: {currentCategory.name}</h2> {}
          {showSuccessMessage && <h3>You've guessed the word!</h3>} { }
          <Word word={selectedWord} guessedLetters={guessedLetters} />
          <Letters onClick={handleLetterClick} guessedLetters={guessedLetters} />
        </div>
      );
}

export default Hangman;
